<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <DebugType>portable</DebugType>
    <DefineConstants>$(DefineConstants);NETCORE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\Machete.X12Schema.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Machete\Machete.csproj" />
    <ProjectReference Include="..\Machete.X12\Machete.X12.csproj" />
  </ItemGroup>
</Project>
