<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <DebugType>portable</DebugType>
    <IsPackable>false</IsPackable>
    <DefineConstants>$(DefineConstants);NETCORE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <ProjectReference Include="..\Machete\Machete.csproj" />
    <ProjectReference Include="..\Machete.X12\Machete.X12.csproj" />
    <ProjectReference Include="..\Machete.X12Schema\Machete.X12Schema.csproj" />
  </ItemGroup>
</Project>
